ALTER TABLE map_pins ADD COLUMN IF NOT EXISTS mood_rating INTEGER DEFAULT 5;
ALTER TABLE map_pins ADD COLUMN IF NOT EXISTS journal_entry_id TEXT;
ALTER TABLE map_pins ADD COLUMN IF NOT EXISTS images TEXT DEFAULT '[]';
