[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTP Headers for security, performance, and compatibility
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Performance headers - cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Override cache for HTML files - short cache for main content
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# TypeScript and JavaScript files
[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "text/x-typescript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "text/x-typescript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Images - longer cache
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
